pool:
  vmImage: "Ubuntu-22.04"
strategy:
  matrix:
    Python38:
      python.version: "3.8"
    Python39:
      python.version: "3.9"
    Python310:
      python.version: "3.10"

trigger:
  tags:
    include:
      - "*"
  branches:
    include:
      - refs/heads/*

pr:
  branches:
    include:
      - "*"

variables:
  # Variables imported from brewblox group:
  # PYPI_USER
  # PYPI_PASSWORD
  - group: brewblox

steps:
  - task: UsePythonVersion@0
    inputs:
      addToPath: true
      versionSpec: "$(python.version)"
      architecture: "x64"

  - bash: |
      pip install poetry
      poetry install
      poetry build
    displayName: Install

  - bash: |
      poetry run pytest
      poetry run flake8
    displayName: Run Pytest

  - bash: |
      pip install twine
      twine upload -u $(PYPI_USER) -p $(PYPI_PASSWORD) --skip-existing dist/*
    displayName: Deploy to PyPi
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), eq(variables['python.version'], '3.7'))
